(function(){
  var urlParams = new URLSearchParams(window.location.search);
  var storedIp = localStorage.getItem('nao_ip') || '10.43.151.105';
  var NAO_API = 'http://' + storedIp + ':5050';

  // Read QID directly from localStorage (generated by pre-questionnaire)
  var questionarioId = urlParams.get('questionario_id') || localStorage.getItem('questionario_id');
  var sessionId = null;

  // Timer
  var _posStartTime = null;

  var TOTAL_SECTIONS = 4;
  var currentSection = 0;

  var progressWrap = document.getElementById('progress-wrap');
  var progressLabel = document.getElementById('progress-label');
  var progressFrac  = document.getElementById('progress-frac');
  var progressFill  = document.getElementById('progress-fill');

  var SECTION_ORDER = ['sec-offer', 'sec-A', 'sec-B', 'sec-C', 'sec-gs-pos'];

  function updateProgress() {
    if(currentSection < 1) {
      if(progressWrap) progressWrap.style.display = 'none';
      return;
    }
    if(progressWrap) progressWrap.style.display = 'block';
    var pct = Math.round((currentSection / TOTAL_SECTIONS) * 100);
    if(pct > 100) {
      progressWrap.style.display = 'none';
    } else {
      if(progressLabel) progressLabel.textContent = 'Se\u00e7\u00e3o ' + currentSection + ' de ' + TOTAL_SECTIONS;
      if(progressFrac) progressFrac.textContent = pct + '%';
      if(progressFill) progressFill.style.width = pct + '%';
    }
  }

  function showSection(idStr) {
    document.querySelectorAll('.q-section').forEach(function(sec){ sec.classList.remove('active'); });
    var s = document.getElementById(idStr);
    if(s) s.classList.add('active');

    if(idStr === 'sec-A') currentSection = 1;
    else if(idStr === 'sec-B') currentSection = 2;
    else if(idStr === 'sec-C') currentSection = 3;
    else if(idStr === 'sec-gs-pos') currentSection = 4;
    else currentSection = 0;

    updateProgress();
    window.scrollTo(0,0);
  }

  // Auto-load participant from localStorage (no code screen needed)
  function loadParticipant() {
    if(!questionarioId) {
      showSection('sec-offer');
      return;
    }
    var offerLabel = document.getElementById('offer-participant-label');
    if(offerLabel) offerLabel.textContent = 'Q' + questionarioId;

    fetch(NAO_API + '/questionario/lista')
      .then(function(r){ return r.json(); })
      .then(function(data){
        if(data.questionarios) {
          for(var i=0; i<data.questionarios.length; i++) {
            var q = data.questionarios[i];
            if(q.id === parseInt(questionarioId, 10)) {
              sessionId = q.session_id;
              break;
            }
          }
        }
        showSection('sec-offer');
      })
      .catch(function(){
        showSection('sec-offer');
      });
  }

  loadParticipant();

  // Offer screen — start timer when accepting
  var btnAccept = document.getElementById('btn-accept-pos');
  if(btnAccept) {
    btnAccept.addEventListener('click', function(){
      _posStartTime = Date.now();
      showSection('sec-A');
    });
  }

  var btnDecline = document.getElementById('btn-decline-pos');
  if(btnDecline) {
    btnDecline.addEventListener('click', function(){
      if(confirm('Tem certeza que n\u00e3o deseja responder o p\u00f3s-question\u00e1rio?')) {
        fetch(NAO_API + '/questionario/desistir', {
          method: 'POST', headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({questionario_id: questionarioId})
        }).catch(function(){});
        localStorage.removeItem('questionario_id');
        showSection('sec-declined');
      }
    });
  }

  // Section A items
  var likertItemsA = [
    {id: 'A1', txt: 'A1. Percebi mudan\u00e7as claras na forma de agir ou de falar do NAO ao longo da partida.'},
    {id: 'A2', txt: 'A2. O NAO demonstrou um perfil Amig\u00e1vel (buscando parceria, comemorando vit\u00f3rias m\u00fatuas e mostrando compreens\u00e3o).'},
    {id: 'A3', txt: 'A3. O NAO demonstrou um perfil Competitivo (com tom provocativo, foco em vencer e irrita\u00e7\u00e3o ao ser contrariado).'},
    {id: 'A4', txt: 'A4. O NAO demonstrou um perfil de Vitimiza\u00e7\u00e3o / \u201cCoitado\u201d (expressando medo, inseguran\u00e7a ou tristeza em suas falas).'},
    {id: 'A5', txt: 'A5. O NAO demonstrou um perfil Neutro (agindo de forma puramente l\u00f3gica, fria e rob\u00f3tica, sem expressar emo\u00e7\u00f5es).'}
  ];

  // Section B items
  var likertItemsB = [
    {id: 'B1', txt: 'B1. Consegui identificar claramente as emo\u00e7\u00f5es do NAO (ex.: alegria, tristeza, confus\u00e3o, medo, agressividade ou provoca\u00e7\u00e3o).'},
    {id: 'B2', txt: 'B2. As rea\u00e7\u00f5es emocionais do NAO combinaram de forma coerente com a escolha que eu e ele fizemos na rodada.'},
    {id: 'B3', txt: 'B3. O tom emocional do NAO fez o jogo parecer mais uma intera\u00e7\u00e3o social do que um teste de l\u00f3gica.'}
  ];

  // Section C items
  var likertItemsC = [
    {id: 'C1', txt: 'C1. Adaptei minha estrat\u00e9gia de jogo em resposta \u00e0s falas e atitudes do NAO.'},
    {id: 'C2', txt: 'C2. Senti que o NAO tentou me enganar ou manipular deliberadamente em alguns momentos.'},
    {id: 'C3', txt: 'C3. As express\u00f5es de emo\u00e7\u00e3o do NAO (como medo ou chatea\u00e7\u00e3o) me fizeram ter pena ou evitar tra\u00ed-lo.'},
    {id: 'C4', txt: 'C4. As provoca\u00e7\u00f5es ou agressividade do NAO me motivaram a tra\u00ed-lo ou retaliar nas rodadas seguintes.'},
    {id: 'C5', txt: 'C5. Experimentei sentimentos reais (como satisfa\u00e7\u00e3o, raiva, culpa ou frustra\u00e7\u00e3o) durante as rodadas.'}
  ];

  function buildLikertGroup(containerId, items) {
    var tbody = document.getElementById(containerId);
    if(!tbody) return;
    items.forEach(function(item){
      var html = '<tr><td class="th-left" style="font-size:.85rem;font-weight:500;line-height:1.5;padding:10px 12px;">' + item.txt + '</td>';
      for(var i=1; i<=5; i++){
        html += '<td style="text-align:center;"><label class="gs-opt"><input type="radio" name="' + item.id + '" value="' + i + '"><div class="gs-bubble">' + i + '</div></label></td>';
      }
      html += '</tr>';
      tbody.innerHTML += html;
    });
  }

  buildLikertGroup('pos-likert-A', likertItemsA);
  buildLikertGroup('pos-likert-B', likertItemsB);
  buildLikertGroup('pos-likert-C', likertItemsC);

  function validateLikert(items) {
    for(var i=0; i<items.length; i++){
      if(!document.querySelector('input[name=' + items[i].id + ']:checked')) return false;
    }
    return true;
  }

  // Section A navigation
  var btnANext = document.getElementById('btn-A-next');
  if(btnANext) {
    btnANext.addEventListener('click', function(){
      if(validateLikert(likertItemsA)) {
        document.getElementById('val-A').style.display = 'none';
        showSection('sec-B');
      } else {
        document.getElementById('val-A').style.display = 'flex';
      }
    });
  }

  // Section B navigation
  var btnBBack = document.getElementById('btn-B-back');
  if(btnBBack) { btnBBack.addEventListener('click', function(){ showSection('sec-A'); }); }
  var btnBNext = document.getElementById('btn-B-next');
  if(btnBNext) {
    btnBNext.addEventListener('click', function(){
      if(validateLikert(likertItemsB)) {
        document.getElementById('val-B').style.display = 'none';
        showSection('sec-C');
      } else {
        document.getElementById('val-B').style.display = 'flex';
      }
    });
  }

  // Section C navigation
  var btnCBack = document.getElementById('btn-C-back');
  if(btnCBack) { btnCBack.addEventListener('click', function(){ showSection('sec-B'); }); }
  var btnCNext = document.getElementById('btn-C-next');
  if(btnCNext) {
    btnCNext.addEventListener('click', function(){
      if(validateLikert(likertItemsC)) {
        document.getElementById('val-C').style.display = 'none';
        showSection('sec-gs-pos');
      } else {
        document.getElementById('val-C').style.display = 'flex';
      }
    });
  }

  // GodSpeed P\u00f3s (full 24 items, 5 categories)
  var gsPosCategories = [
    {category: 'Caracter\u00edsticas Humanas do Rob\u00f4: Antropomorfismo', items: [
      ['Falso', 'Natural'],
      ['Com aspecto mec\u00e2nico', 'Com aspecto humano'],
      ['Inconsciente', 'Consciente'],
      ['Artificial', 'Realista'],
      ['Move-se com rigidez', 'Move-se com fluidez']
    ]},
    {category: 'Impress\u00e3o de Vida e Rea\u00e7\u00e3o do Rob\u00f4: Animacidade', items: [
      ['Morto', 'Com vida'],
      ['Parado', 'En\u00e9rgico'],
      ['Mec\u00e2nico', 'Org\u00e2nico'],
      ['Artificial', 'Realista'],
      ['Est\u00e1tico', 'Interativo'],
      ['Ap\u00e1tico', 'Participativo']
    ]},
    {category: 'Impress\u00e3o Geral sobre o Rob\u00f4: Simpatia', items: [
      ['N\u00e3o gosto', 'Gosto'],
      ['Hostil', 'Amig\u00e1vel'],
      ['Antip\u00e1tico', 'Gentil'],
      ['Desagrad\u00e1vel', 'Agrad\u00e1vel'],
      ['Horr\u00edvel', 'Simp\u00e1tico']
    ]},
    {category: 'Capacidade Percebida do Rob\u00f4: Intelig\u00eancia Percebida', items: [
      ['Incompetente', 'Competente'],
      ['Ignorante', 'Sabedor'],
      ['Irrespons\u00e1vel', 'Respons\u00e1vel'],
      ['Pouco inteligente', 'Inteligente'],
      ['Insensato', 'Sensato']
    ]},
    {category: 'Sensa\u00e7\u00e3o Durante a Intera\u00e7\u00e3o: Seguran\u00e7a Percebida', items: [
      ['Ansioso', 'Descontra\u00eddo'],
      ['Agitado', 'Calmo'],
      ['Sereno', 'Surpreendido']
    ]}
  ];

  var gsPosTbody = document.getElementById('gs-pos-tbody');
  var gsPosTotal = 0;
  if(gsPosTbody){
    gsPosCategories.forEach(function(cat){
      gsPosTbody.innerHTML += '<tr><td colspan="7" style="font-weight:700; background:var(--gold-soft); padding:8px 12px; text-align:center;">' + cat.category + '</td></tr>';
      cat.items.forEach(function(p){
        gsPosTotal++;
        var n = gsPosTotal;
        var html = '<tr><td class=th-left><div class=gs-label>' + p[0] + '</div></td>';
        [1,2,3,4,5].forEach(function(val){
          html += '<td><label class=gs-opt><input type=radio name=gs_pos_' + n + ' value=' + val + '><div class=gs-bubble>' + val + '</div></label></td>';
        });
        html += '<td class=th-right><div class="gs-label right">' + p[1] + '</div></td></tr>';
        gsPosTbody.innerHTML += html;
      });
    });
  }

  var btnGsPosBack = document.getElementById('btn-gs-pos-back');
  if(btnGsPosBack) { btnGsPosBack.addEventListener('click', function(){ showSection('sec-C'); }); }

  var btnGsPosSubmit = document.getElementById('btn-gs-pos-submit');
  if(btnGsPosSubmit) {
    btnGsPosSubmit.addEventListener('click', function(){
      var isValid = true;
      for(var i=1; i<=gsPosTotal; i++){
        if(!document.querySelector('input[name=gs_pos_'+i+']:checked')) { isValid = false; break; }
      }
      if(!isValid) {
        document.getElementById('val-gs-pos').style.display = 'flex';
        return;
      }
      document.getElementById('val-gs-pos').style.display = 'none';
      btnGsPosSubmit.disabled = true;
      btnGsPosSubmit.textContent = 'Enviando...';

      var tempoPosSegundos = _posStartTime ? Math.round((Date.now() - _posStartTime) / 1000) : null;
      var tempoJogoSegundos = localStorage.getItem('tempo_jogo_segundos');
      tempoJogoSegundos = tempoJogoSegundos ? parseInt(tempoJogoSegundos, 10) : null;

      var payload = {
        questionario_id: questionarioId,
        session_id: sessionId,
        tempo_pos_segundos: tempoPosSegundos,
        tempo_jogo_segundos: tempoJogoSegundos
      };

      likertItemsA.forEach(function(item){
        payload[item.id] = parseInt(document.querySelector('input[name='+item.id+']:checked').value, 10);
      });
      likertItemsB.forEach(function(item){
        payload[item.id] = parseInt(document.querySelector('input[name='+item.id+']:checked').value, 10);
      });
      likertItemsC.forEach(function(item){
        payload[item.id] = parseInt(document.querySelector('input[name='+item.id+']:checked').value, 10);
      });
      for(var i=1; i<=gsPosTotal; i++){
        payload['godspeed_pos_'+i] = parseInt(document.querySelector('input[name=gs_pos_'+i+']:checked').value, 10);
      }

      fetch(NAO_API + '/questionario/pos', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      })
      .then(function(r){ if(!r.ok) throw new Error(); return r.json(); })
      .then(function(data){
        localStorage.removeItem('questionario_id');
        localStorage.removeItem('tempo_jogo_segundos');
        showSection('sec-done');
      })
      .catch(function(err){
        alert('Erro ao enviar question\u00e1rio. Verifique o servidor.');
        btnGsPosSubmit.disabled = false;
        btnGsPosSubmit.textContent = 'Enviar Respostas';
      });
    });
  }

})();
